### ISSUE TITLE
building automake 1.13 persistently fails

### ISSUE THREAD

**Issue by Geertsky** [conda-forge/automake-feedstock#34]
### Comment:

Hi
I have been trying to create a conda package for automake 1.13 but anything I try fails...
I'm getting a build problem about help2man.
```
help2man: can't get `--help' info from aclocal-1.13                                                                                               
Try `--no-discard-stderr' if option outputs to stderr                                                                                             
make: *** [Makefile:4276: doc/aclocal-1.13.1] Error 2
```

I've googled around and only got some pointers on perl versions or perl shebang problems that shouldn't be related.
Additionally, I'm able to compile it by hand when I activate the build environment.
Does anyone have any suggestions what I could try? 
My recipe:
```
{% set version = "1.13.4" %}
{% set sha256sum = "4c93abc0bff54b296f41f92dd3aa1e73e554265a6f719df465574983ef6f878c" %}
package:
  name: automake
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - perl 5.32.1

requirements:
  build:
    - make
  host:
    - m4
    - autoconf
    - perl=5.32.1
    - make
  run:
    - m4
    - autoconf
    - perl=5.32.1

test:
  commands:
    - automake --help

about:
  home: http://www.gnu.org/software/automake/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Tool for automatically generating Makefile.in files compliant with the GNU Coding Standards.
  description: |
    Automake is a tool for automatically generating Makefile.ins from files
    called Makefile.am.  It assumes that the project uses Autoconf and enforces
    certain restrictions on the configure.ac contents.
  dev_url: https://git.savannah.gnu.org/git/automake.git
  doc_url: https://www.gnu.org/software/automake/manual/automake.html
  doc_source_url: http://git.savannah.gnu.org/cgit/automake.git/tree/doc

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - mingwandroid
```

My build script:
```
#!/bin/sh

./configure --prefix=$PREFIX
make
make install
```
